POST https://back-end-ue5hunfyyq-ew.a.run.app/passengers HTTP/1.1
content-type: application/json

{"name":"Burak", "location": "7.cadde"}

###

GET http://localhost:3000/passengers/62ff21afb8951bc52ab032f7 HTTP/1.1

###
DELETE http://localhost:3000/passengers/630a6c1943713a00cb40e26c HTTP/1.1

###

PATCH http://localhost:3000/passengers/5e9de4cd9f11eb7402e56941 HTTP/1.1
content-type: application/json

{"name": "new name4"}

###

POST https://back-end-ue5hunfyyq-ew.a.run.app/drivers HTTP/1.1
content-type: application/json

{"name":"Ahmet", "age": 35, "location": "Bilkent"}

###
DELETE http://localhost:3000/drivers/5ea70bf063b0877147bd3e6b HTTP/1.1

###
POST http://localhost:3000/passengers/62ff31ad941cd7fb0061b079/bookings HTTP/1.1
content-type: application/json

{"driverId": "62ff21f1b8951bc52ab032fc", "origin": "asdada", "destination": "asdasda"}

###

PATCH http://localhost:3000/drivers/5ea70c8063b0877147bd3e6c HTTP/1.1
content-type: application/json

{"name": "a newer surname"}